/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiktok.profile.extract.processor;

import org.junit.jupiter.api.Test;

import com.romys.tiktok.profile.extract.processor.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
